[package]
name = "tls"
version = "0.0.0"
workspace = "../"
edition = "2021"
publish = false

[dependencies]
rocket = { path = "../../core/lib", features = ["tls", "mtls", "secrets", "http3"] }
yansi = "1.0.0-rc.1"
